apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-todoapp
  namespace: mateapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
     app: mateapp
  template:
    metadata:
      labels:
        app: mateapp
    spec:
     containers:
     - name: todoapp
       image: trinida/todoapp:4.0.1
       resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "400m"
       ports:
       - containerPort: 8080
       env:
       - name: EXTERNAL_ENDPOINT
         value: "http://httpbin-api.mateapp.svc.cluster.local"
       livenessProbe:
         httpGet:
           path: api/health
           port: 8080
         initialDelaySeconds: 60
         periodSeconds: 5
       readinessProbe:
         httpGet:
           path: api/ready
           port: 8080
         initialDelaySeconds: 5
         periodSeconds: 5
